### ISSUE TITLE
[Bug]: Device property not updated after changing it in the app

### ISSUE THREAD

**Issue by Palmke** [bropat/eufy-security-client#122]
### Client version

1.6.6

### Node version

16

### Operating System type

Docker

### Operating system version

Alpine (from the client-ws Dockerfile)

### Describe the bug

It seems that (at least) the rotation speed field for the Indoor Cam T8410 is not updated when changed in the app.
I had set it to 5 through the client, then later set it to 3 in the app. I can see on https://mysecurity.eufylife.com/ that the parameter value has changed to 3, but in the client, it remains 5.

I have waited until after the polling interval occurs (5 minutes) but no dice. When restarting the client, the property is set correctly.

### To reproduce

Set rotation to 5 through the client, then later set it to 3 in the app.
Observe that on https://mysecurity.eufylife.com/ the parameter value has changed to 3, but in the client, it remains 5.
Wait until after the polling interval occurs and observe that it is stlil 5.

**Comment by bropat** [comment]
@Palmke 

I think the problem is that I track the timestamp of the last change for each parameter and when synchronising the data via the Eufy Cloud, the timestamp value received is not always up to date (eufy does not always update the timestamp values!) and therefore the value of the respective parameter may be new but due to the old timestamp, this value is then ignored by eufy-security-client.
I will have to come up with another update strategy ;)

**Comment by Palmke** [comment]
Well, I assume instead of checking the timestamp you can check the values of the parameter if it's a number or boolean. Should cost the same amount of resources.
