### ISSUE TITLE
Capture picture over P2P 

### ISSUE THREAD

**Issue by yooo1999** [bropat/eufy-security-client#181]
Please add an option to take a snapshot  over P2P session

Thank you!

**Comment by thieren** [comment]
Hi @yooo1999 

I am not sure whether @bropat would like to add the necessary dependencies to his library. I would think that this is merely out of scope of this project and more a use case for projects using this library.

But then again he can say himself if he thinks otherwise.

Nevertheless I'd like to point you to this [example code](https://github.com/thieren/Homebridge-eufy-plugin/blob/89a55af4736a08c0d845f8dd3986fa6f34c66d25/src/plugin/accessories/SnapshotManager.ts#L435-L514) how we handled this requirement in the homebridge plugin. Maybe this helps you.

**Comment by bropat** [comment]
Agree completely with @thieren.
