### ISSUE TITLE
[Feature request]: alarm delay on calling triggerStationAlarmSound

### ISSUE THREAD

**Issue by thieren** [bropat/eufy-security-client#191]
### Describe the solution you'd like

We utilize [`triggerStationAlarmSound`](https://github.com/bropat/eufy-security-client/blob/54f94083592feeeaf8e53ab77b521f4cd62aea04/src/http/station.ts#L2474-L2502) in our homebridge plugin to let the user have a way to manually set off the alarm. This could for example be used with automations to trigger the alarm when a sensor from a third party vendor fires an event.

However the way it is implemented now the alarm delay setting is not used within this method. Maybe this could be added?
Probably a request for @Palmke ?

**Comment by Palmke** [comment]
I'm not sure how @bropat views these features. So far the client mostly is just a proxy for the events and settings in the app.
Custom logic would break with that tradition. 
For example, I created a X/Y coordinate system for my pan-tilt cameras but that's custom logic I built outside of this client.

Aside from that I'm not sure I am the right person to create that custom logic, node isn't my "first language" ;-)

**Comment by thieren** [comment]
Ok, I understand that. Then the other way around: Is there a way to get the value that the user has configured for these settings currently? So I could implement it in the plugin.

e.g. the user has set it to away mode, and I can read the value for arm delay and delay on leave so that I can program the behaviour of the plugin accordingly.

**Comment by Palmke** [comment]
Actually, you can use the recently added mode data for that ;-)
When the alarm mode changes, an event is emitted: https://github.com/bropat/eufy-security-client/blob/develop/src/http/station.ts#L563
Based on the active alarm mode, you can map which security settings data is active and get the delay values from there: https://github.com/bropat/eufy-security-client/blob/develop/src/http/station.ts#L577

For your use case use `count_down_alarm` instead of `count_down_arm`.

**Comment by bropat** [comment]
As @Palmke already suggests
