### ISSUE TITLE
Corrupt videoStream is received on the start_livestream event

### ISSUE THREAD

**Issue by davyrolink** [bropat/eufy-security-client#2]
**Describe the bug**  
Corrupt videoStream is received on the start_livestream event (blockiness/colour artifacts).

**To Reproduce**
1. git clone git@github.com:davyrolink/eufy-test-stream.git
2. cd eufy-test-stream
3. nano src/App/Parameters.ts (edit this file; enter your username, password and cameraDeviceId)
4. npm install
5. npm run start-dev (takes +/- 15sec)
6. ffplay output/test-stream.dump (ffplay / ffmpeg must be installed)

The video stream that is captured is corrupt and shows blockiness/colour artifacts.

**Expected behavior**  
A video stream dump without artifacts.

**Screenshots & Logfiles**  
![test-stream dump example01](https://user-images.githubusercontent.com/5167555/111080547-38d5e180-84ff-11eb-836a-55405b340edf.jpg)

**Versions:**  
 - eufy-security-client: 0.6.0
 - Operating system: macOS
 - Device: Battery Doorbell 2K (T8210)

**Additional context** 
The Eufy app settings for the camera "Video Quality" make a difference to the amount of corruption.
Worst case: Steaming Quality -> High, Video Encoding Format -> High

The problem is almost not visible during night time (black&white), only some small artifacts

**Comment by bropat** [comment]
Hi @davyrolink ,
I think I have found the error. I am working on fixing it. As soon as I have a test version available I will let you know (unfortunately I don't have a doorbell to test).

**Comment by bropat** [comment]
Hi @davyrolink,
please try the attached version 0.6.1 and let me know if the problem is fixed.

PS: Please rename attached file to eufy-security-client-0.6.1.tgz (.tgz is an unsupported attachment file on github).

[eufy-security-client-0.6.1.tgz.zip](https://github.com/bropat/eufy-security-client/files/6159529/eufy-security-client-0.6.1.tgz.zip)

**Comment by davyrolink** [comment]
Hi @bropat,

I just tested the new version, but unfortunately the issue seems unchanged. I sent you a mail to your gmail mail address to exchange some additional debug details.

**Comment by bropat** [comment]
Hi @davyrolink ,

one reason for this glitch could also be the change of resolution during the stream, because Eufy provides that the resolution and FPS are adjusted depending on the connectivity.  This is of course not handled by ffplay. From the source code I see that behind the scenes Eufy reinitializes and restarts the stream when it detects that the resolution has changed.

PS: If you enable the debug logs you can also see if the resolution has changed at runtime.

**Comment by bropat** [comment]
@davyrolink 

I tested it with version 0.8.1 and it seems to work:

![image](https://user-images.githubusercontent.com/2305255/118390744-ffba0a80-b630-11eb-9dfe-758b8fc3b876.png)

Did you change something on your side? Some settings of the doorbell? Like for example the watermark setting?

**Comment by davyrolink** [comment]
@bropat I just updated my test repo ( https://github.com/davyrolink/eufy-test-stream ) to use 0.8.1

Unfortunately the issue seems unchanged for me, first few seconds ok, then artifacts/corruption..

![eufy_20210516_110432](https://user-images.githubusercontent.com/5167555/118391966-40b51d80-b637-11eb-9686-d40f927e3837.jpg)

**Comment by bropat** [comment]
@davyrolink 

Good news, finally found and fixed the issue after deep troubleshooting. :)

**Comment by davyrolink** [comment]
Great work @bropat !! I can confirm that this resolves the issue, thanks 👍
