### ISSUE TITLE
[Feature request]: Programmatically add access to lock

### ISSUE THREAD

**Issue by bbedwell** [bropat/eufy-security-client#204]
### Describe the solution you'd like

I own and manage an Airbnb and use the Eufy smart lock for access to our condo. Would it be possible using this library to programmatically add new people to the access list for the smart lock? I'm more than happy to actually implement the changes necessary but would need to be pointed in the right direction. I don't currently see this as a supported feature.

Edit: more specifically, I’m not wanting to add other eufy users but add codes programmatically. It’s functionality that exists in the current app. I don’t want to share access. This is how I’m currently doing it but it’s a manual process.

**Comment by thieren** [comment]
Hi @bbedwell 

just a user, but giving my 2 cents here:

I don't think eufy devices can be shared the way you describe. At least your guests would need at least an eufy account and the app to use the lock. And the methods to invite users are not implemented in this library I think.

What would be theoretically possible, would be to build your own server with user accounts that deals with the lock communication in the background via this library (e.g. wrapping the eufy functionality up into your server).
But coding the server would be up to you, since this is out of scope of this project.

Also I'd be aware of the security implications this might have. Since a poorly written server might expose your lock in a way that you definitely do not want.

**Comment by bropat** [comment]
If this functionality is included in the app, I can also add it to the library. But for that I need access to the device.

**Comment by bropat** [comment]
If you would like to share the device with me:

* [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com) (for EU)
* [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)

Thanks!

**Comment by fabianluque** [comment]
@bropat Did someone already share access with you? If not, let me know and I can share mine.

**Comment by bropat** [comment]
@fabianluque 

No one yet.

**Comment by fabianluque** [comment]
@bropat Just shared my T8520 lock with you. Let me know when you’re done.

**Comment by bbedwell** [comment]
@bropat sorry I am unable to share with you as the location of the lock is in a ver

**Comment by bropat** [comment]
**Small update:**

Thanks to @fabianluque, almost all the desired functionalities have now been roughly implemented. These still need to be refined and tested.

**Comment by fabianluque** [comment]
@bropat Thank you! You still need access for a few more days?

**Comment by bropat** [comment]
@fabianluque yes, please.
I will let you know as soon as I no longer need it.

**Comment by bropat** [comment]
@fabianluque 

I no longer need access. Thx!

**Comment by fabianluque** [comment]
@bropat Thank you!
