### ISSUE TITLE
What is this client for ?

### ISSUE THREAD

**Issue by balajeek** [bropat/eufy-security-client#266]
### Ask your question

I am trying to understand what this does, it says its client to access security devices (like cameras) using the eufy cloud account, but why.  Also i did not find any clear instructions to how set this up and what the end result is. no screenshots.

I was googling to see if i could update my eufy floodlight pro camera to custom firmware so i can stream 24/7 instead of events only, and ended up on this github and trying to find if its something for me.

any help would be appreciated.  Thanks.

**Comment by thieren** [comment]
Hi @balajeek 

This client is basically a reverse engineered version of the official eufy app, without the gui and some other 'features' like ads.
It aims to let you do the basic connection/interactions to your eufy cameras with a node based client - so you have more control on what you'd like to do.

The way I use it is to utilise it in a [homebridge plugin](https://github.com/homebridge-eufy-security/plugin), which let's me add eufy devices to Apples Home App although these devices have no native support for that.

You won't be able to update your eufy camera with a custom firmware with this.
But in theory it would be able to write a program that lets you stream with your camera 24/7 with this client. At least you could use it to reestablish the stream as soon as the old one dies due to timeout.

But also to my experience it is not feasible to use eufy cameras for 24/7 streaming. I have not experience with the floodlight though, so you may be good with this one.

**Comment by balajeek** [comment]
Sounds great and would like to give it a try.  I have a ubuntu os running for all my docker containers.  I also have hass,node-red in docker.  what can I do to start?

**Comment by thieren** [comment]
Unfortunately there is not much of documentation (see #1). So you'll have to take a look at sample projects and figure out how to use the client.
It's really not that hard once you get the hang of it.

An example as starting point would be [eufy-security-ws](https://github.com/bropat/eufy-security-ws)
