### ISSUE TITLE
[Feature request]: Support T8530/S330 Video Smart Lock

### ISSUE THREAD

**Issue by BoiseITGuru** [bropat/eufy-security-client#270]
### Describe the solution you'd like

Please add support for the T8530/S330 (HomeBridge shows the model as T8530 but the device itself says S330) Video Smart Lock.

Happy to provide any additional information you may need or to perform testing.

**Comment by j-coates** [comment]
Submitted here, waiting for the dev to have time: https://github.com/bropat/eufy-security-client/issues/220

**Comment by flacco54** [comment]
I am looking for this also, but just to confirm this is the product?
https://us.eufy.com/products/e85301y1?ref=navimenu_3_img

**Comment by timmerk** [comment]
@bropat I can share access if that helps.. thanks!

**Comment by ShonGee** [comment]
I also can share the device. Looking forward to support. Thanks.

**Comment by jevins09** [comment]
@bropat Any updates on this issue? Is this on the roadmap?  I can also share access if that helps. I'd also be willing to help with the development if needed.

**Comment by dmuhamma** [comment]
Also looking forward to support for this device. I’m in Canada and can share device as well.

**Comment by ericwittkopp** [comment]
Awesome plugin.  Can't wait for this device to be supported!  As with everyone else, I am happy to help when ready, if needed.

**Comment by FaberO42** [comment]
Awesome work on this bropat and +1 for this feature request 👍 :)

**Comment by ncuscadd** [comment]
super keen on this one also. Shout out if there is anything I can do to help

**Comment by paulbaird87** [comment]
Happy to be the guinea pig to integrate this device, mine is one of the only smart devices in my home not communicating with HA.

**Comment by kineticscreen** [comment]
I'm surprised that this product hasn't even been added to the list of devices, even to just show a red cross that it isn't currently supported...

**Comment by paulbaird87** [comment]
Hello from Australia @BoiseITGuru. I would like to share with you my current workaround for unlocking this door through HA. Also would love to learn the process of integrating something like this into HA. Have you ever made a video or guide on this?

Current (desperate) automation process:
- Wifi detects phone.
- Automation sends HA app notification to spare Android phone (dedicated to this one and only job)
- Macrodroid detects HA app notification
- Macordrpoid runs macro to open Eufy app then long press unlock in app.
- If zigbee sensor door state changes from open to closed HA sends Google SDK command to lock the door. 
- Otherwise door stays unlocked for 3 mins (max allowed in eufy app auto ock settings).

I hope this helps anyone else with the Eufy 3in1 doorbel/lock/cam.

**Comment by rlippmann** [comment]
+1, will also provide device access/debugging/etc.

**Comment by LiyuanLucasLiu** [comment]
+1 here

**Comment by bropat** [comment]
Look [here](https://github.com/bropat/eufy-security-client/issues/220).
