### ISSUE TITLE
[Question]: Why do motion sensors not trigger when notifications are turned off.

### ISSUE THREAD

**Issue by bartcuijpers** [bropat/eufy-security-client#498]
### Ask your question

I noticed the following behavior; I have door sensors and motion sensors in my home. The door sensors always trigger, even when 'push notifications' are turned off in the Eufy app. For some reason the motion sensors only trigger when push notifications are turned on.

I would like to use them in my HA automations without getting hundred push notifications on a daily basis. Would this be possible?

Thanks!

**Comment by jesse-kaufman** [comment]
Disable the Eufy app notifications at the OS level instead of in the app (Settings->Notifications on iOS or the equivalent in Android).

That keeps everything working in HA without being inundated with hundreds of notifications :) Then, you can create whatever notifications you _actually_ want in your automations. It works great for me and I have complete control over which notifications I receive!  

All the Eufy cameras I have require notifications in the app to be enabled for the motion sensors to update in HA. Sounds like the door sensors work differently for whatever reason.

**Comment by t9001** [comment]
Wondering if anyone found a solution to this. My door and motion sensors both need notifications to be enabled for Home Assistant to receive their activity. Otherwise the door sensor in HA just stays "closed" and the motion sensor stays "clear". I would like HA to keep track of motion and door openings for automation purposes.

No way I can have notifications on in the Eufy app for these devices when the system is in "Home" mode, my phone would explode. However, I do need notifications on for the Eufy app as a whole. Turning them off at the OS level isn't an option for me.
