### ISSUE TITLE
Can't configure the plugin in Homebridge

### ISSUE THREAD

**Issue by JPF-dot** [bropat/eufy-security-client#7]
I’m a total newbie to this so please apologize for the stupid questions. 
I've installed homebridge on a raspberry pi and wanted to install your Eufy Security Client plugin.
So I used the command : npm install Eufy-security-client and got it on the system.
But I can’t see it listed in the homebridge plugin list or neither access any UI to configure the plugin. 

I guess there is something I’m doing wrong or maybe it isn’t ready yet to function on homebridge ? 
I would love your advice and guidance to help me set up my battery video doorbell with homebridge.

I’m using this plugin for now : https://github.com/birkir/homebridge-plugin-eufy-security
But wasn't really satisfied as it won’t stream the video in HomeKit. 

I wanted to give your plugin a try. 

Any help is welcome 

thanks

**Comment by bropat** [comment]
Hi, this is a low-level client library. It is not a Homebridge plugin.The mentioned Homebridge plugin could switch to use my low-level client library to provide more features, like local livestream via P2P interface and so on. Regards,Patrick Von: JPF-dotGesendet: Freitag, 9. April 2021 00:15An: bropat/eufy-security-clientCc: SubscribedBetreff: [bropat/eufy-security-client] Can't configure the plugin in Homebridge (#7) I’m a total newbie to this so please apologize for the stupid questions.I've installed homebridge on a raspberry pi and wanted to install your Eufy Security Client plugin.So I used the command : npm install Eufy-security-client and got it on the system.But I can’t see it listed in the homebridge plugin list or neither access any UI to configure the plugin.I guess there is something I’m doing wrong or maybe it isn’t ready yet to function on homebridge ?I would love your advice and guidance to help me set up my battery video doorbell with homebridge.I’m using this plugin for now : https://github.com/birkir/homebridge-plugin-eufy-securityBut wasn't really satisfied as it won’t stream the video in HomeKit.I wanted to give your plugin a try.Any help is welcomethanks—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by deanlyoung** [comment]
@bropat I am working on porting it over here: https://github.com/deanlyoung/homebridge-eufy-security, but it looks like a few methods and interfaces changed between `eufy-security-client` and the former `eufy-node-client`...

Do you have any recommendations for these portions:
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L10
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L92
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L177
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L190
