### ISSUE TITLE
T8420 Floodlight: certain properties don't work properly 

### ISSUE THREAD

**Issue by fullphat** [bropat/eufy-security-client#72]
I'm using the HomeBridge plugin (which uses this library) for a T8420 Floodlight Camera and I'm getting lots of errors like this:

```handleEnableGet Wrong return value```

I've looked at the plugin code and it seems it's actually an issue with this library as the plugin is calling `Camera.getPropertyValue(PropertyName.DeviceEnabled);` which is throwing an exception that the plugin is catching.  It's throwing the exception as `getPropertyValue()` isn't finding a property called `enabled`.

**EDIT:** Have been doing some digging around, although neither Node nor Javascript is my happy place 🙂 and, from what I can see, the T8420 doesn't seem to support the 'enabled' (ID2001) or 'motion detection' (ID6040) properties. 

I'm only basing this on looking at `Device.metadata`, `Device.rawProperties` and `Device.properties` so I may well be way off here!   Is anyone able to confirm?

**Comment by smitty078** [comment]
I'm seeing this issue as well.

At this point, I've got the motion detection property working by changing "DeviceMotionDetectionIndoorSoloFloodProperty" to "DeviceMotionDetectionProperty" and "DeviceMotionDetectionIndoorSoloFloodProperty" to "DeviceMotionDetectedProperty" on lines 1907 and 1909 respectively in http/types.js 

I have yet to be able to get DeviceEnabled working, despite changing the properties to ones that work on other camera models.

I find it hard to believe that this never worked, and I therefore conclude the Eufy made a change either server-side or with a firmware update that broke support. It seems to be a matter of finding the correct properties that correspond to the new properties that are being used. The code in this library is easy enough to follow, but I have not found a good way to simply poke at properties for debugging purposes. Perhaps there's a simple project wrapped around this library that I'm not aware of? If not - maybe I'll build one...

**Comment by fullphat** [comment]
Thanks - I'll try the same.  I've been focusing more on the enabled property but if I can get one of them working, that'll be a good start.  I'm using the beta plugin as that supports the floodlights and it seems to work well.  Sadly, it looks like it (or the upstream library) doesn't support non-RTSP P2P streaming just yet).

On a side note, do you know of a way to get debug logs from the upstream library to display in HomeBridge?

**Comment by smitty078** [comment]
If you take a look, I linked a pull request to this bug that resolves (I believe) all of the broken properties, including DeviceEnabled.

Next on my list is to fix streaming. I'm using the beta Homebridge plugin as well and am not able to get any streaming working out of the box. I've got some leads and might have a pull request ready for tonight.

For showing logs from this library in the Homebridge log use `this.log = console;` to replace line 47 'this.log = log;' in eufysecurity.js - be aware it dumps A LOT of logs and Homebridge does not clear/archive its log file at all, so you may want to do this manually periodically. Logging also seems to slow things down quite a bit, so I only would use this temporarily for debugging.

**Comment by fullphat** [comment]
Thanks for the tip on logging - I might leave it alone for now.  I manually applied the changes you made but I might have missed something as the "enabled" switch isn't working and the "camera status LED" is always "on" in HomeKit (not that it really matters), although motion detection now seems fixed.

Getting streaming working would be awesome! 👍🏼

**Comment by smitty078** [comment]
Glad you got it working - I’ll have to take another look at device status led - I hadn’t noticed that one as not working.

I am able to get camera streaming working but it’s a bit complicated because it requires changes both to the library AND to the HomeKit plugin. Also technically one of the issues is a permissions issue that can be worked around in code or solved on the local machine (affects macOS for sure, don’t know about others) so I have some decision making to do on implementation… I’ll probably attempt to reach the developers before posting any kind of a patch

**Comment by fullphat** [comment]
Ok - if you can share info here (or separately somehow) I'd be keen to try it out.  Great to hear that it's do-able though!

**Comment by bropat** [comment]
Hi,

sorry for the late reply.
The problem with the floodlight devices is that not every device has the same properties (e.g. T8423 has different properties than the others).
From my point of view, Eufy has different development teams, because depending on the device, some properties match and some don't (this refers to all Eufy devices, not just Floodlights).
Without devices it is impossible to guarantee that everything always works.
Furthermore, it is easily possible that these properties are also changed by firmware updates...
What I can guarantee you is that when I had the respective devices available through sharing and I implemented them, all properties always worked.

At the moment I was provided with a Floodlight T8423, maybe you can find the remaining devices (T8422, T8424, T8420), so I can check them all again and if necessary correct what doesn't work anymore.

**Comment by fullphat** [comment]
Thanks bropat and I agree that there are different developers at play as the T8420 seems very different to the P&T 2Ks I have, not least the lack of RTSP!

At the moment I'm not really able to share access to the device, but I'm happy to do some diagnostics/checks if that's of any use?

**Comment by bropat** [comment]
I now fully support the Eufy Floodlight Cam 2 Pro (T8423).

I can check the Eufy Floodlight (T8420) completely here again if someone shares their device for a maximum of one day.

Could someone share their device with me on one of the following accounts:

* patrick.broetto+eu2@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

Let me know.

**Comment by fullphat** [comment]
I can share my T8420 for a day.  Let me know when's good!  I'll be on the EU server.

**Comment by bropat** [comment]
@fullphat 

I need admin rights so that I can test and integrate everything. Unfortunately I can't do it with Guest.

**Comment by fullphat** [comment]
Sorry!  New invite sent...

**Comment by bropat** [comment]
@fullphat 

I no longer need access. Thank you!

New version (1.5.0) with full support released.
